name: "test"
description: "test"
inputs:
  some:
    required: false
    default: ''
    description: "Some"
runs:
  using: composite
  steps:
    - name: "Debug"
      env:
        INPUTS: ${{ toJSON(inputs) }}
        SOME: ${{ inputs.some }}
      shell: bash
      run: |
        echo "${INPUTS}"
        echo "x${SOME}x"

    - run: echo "empty"
      if: ${{ inputs.some == '' }}
      shell: bash
    - run: echo "not empty"
      if: ${{ inputs.some != '' }}
      shell: bash
    - run: echo "null"
      if: ${{ inputs.some == null }}
      shell: bash
    - run: echo "not null"
      if: ${{ inputs.some != null }}
      shell: bash
