name: "test"
description: "test"
inputs:
  some:
    required: false
    default: "Hello"
    description: "Some"
runs:
  using: composite
  steps:
    - name: "Debug"
      env:
        SOME: ${{ inputs.some }}
      shell: bash
      run: echo "${SOME}"
