name: "Input as env"
description: "Uses input JSON as environment for execution."

inputs:
  envs:
    description: 'JSON-encoded object which contains environment variables.'
    required: true

runs:
  using: composite
  steps:

    - name: "Output env"
      shell: bash
      run: env | grep GHA_TEST_

    - name: "Output env with inputs"
      shell: bash
      run: env | grep GHA_TEST_
      env: ${{ fromJSON(inputs.envs) }}
