name: "Reusable Action Tests"
on:
  push:

jobs:
  actions:
    name: "Action tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: ".github/actions/reusable-action-standard"
        uses: ./.github/actions/reusable-action-standard@shared

      - name: ".github/actions/sub/reusable-action-substandard"
        uses: ./.github/actions/sub/reusable-action-substandard@shared

      - name: ".github/reusable-action-github"
        uses: ./.github/reusable-action-github@shared

      - name: ".github/shared/reusable-action-subgithub"
        uses: ./.github/shared/reusable-action-subgithub@shared

      - name: ".github/workflows/reusable-action-workflow"
        uses: ./.github/workflows/reusable-action-workflow@shared

      - name: ".github/workflows/shared/reusable-action-subworkflow"
        uses: ./.github/workflows/shared/reusable-action-subworkflow@shared

      - name: ".github/workflows/actions/reusable-action-looking"
        uses: ./.github/workflows/actions/reusable-action-looking@shared

      - name: ".github/workflows/actions/sub/reusable-action-sublooking"
        uses: ./.github/workflows/actions/sub/reusable-action-sublooking@shared

      - name: "reusable-action-folder"
        uses: ./reusable-action-folder@shared

      - name: "shared/reusable-action-subfolder"
        uses: ./shared/reusable-action-subfolder@shared

