name: "Android"
on:
  workflow_dispatch:
  push:
jobs:
  versions-2204:
    name: "Android Versions on Ubuntu 22.04"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: "Default Android versions"
        run: |
          which sdkmanager || true
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --version
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --list | tee default.txt

      - name: "Use setup-android Action"
        uses: android-actions/setup-android@v3

      - name: "setup-android Android versions"
        run: |
          which sdkmanager
          sdkmanager --version
          sdkmanager --list | tee setup-android.txt

      - name: "Difference between default and setup-android Android versions"
        run: diff default.txt setup-android.txt

  versions-mac:
    name: Android Versions on MacOS
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: "Default Android versions"
        run: |
          which sdkmanager || true
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --version
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --list | tee default.txt

      - name: "Use setup-android Action"
        uses: android-actions/setup-android@v3

      - name: "setup-android Android versions"
        run: |
          which sdkmanager
          sdkmanager --version
          sdkmanager --list | tee setup-android.txt

      - name: "Difference between default and setup-android Android versions"
        run: diff default.txt setup-android.txt

  versions-win:
    name: Android Versions on Windows
    runs-on: windows-latest
    timeout-minutes: 1
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: "Default Android versions"
        run: |
          where sdkmanager
          %ANDROID_SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager.bat --version
          %ANDROID_SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager.bat --list

      - name: "Use setup-android Action"
        uses: android-actions/setup-android@v3

      - name: "setup-android Android versions"
        run: |
          where sdkmanager
          sdkmanager --version
          sdkmanager --list

      - name: "Difference between default and setup-android Android versions"
        run: |
          echo 1 | tee default.txt
          echo 2 | tee setup-android.txt
      - name: "Difference between default and setup-android Android versions"
        run: diff default.txt setup-android.txt

  versions-2004:
    name: Android Versions on Ubuntu 20.04
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: "Default Android versions"
        run: |
          which sdkmanager || true
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --version
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --list | tee default.txt

      - name: "Use setup-android Action"
        uses: android-actions/setup-android@v3

      - name: "setup-android Android versions"
        run: |
          which sdkmanager
          sdkmanager --version
          sdkmanager --list | tee setup-android.txt

      - name: "Difference between default and setup-android Android versions"
        run: diff default.txt setup-android.txt
