# https://github.com/lannonbr/linting-checks-workflow/blob/master/.github/workflows/lint.yml

name: Custom Check Run Action
on:
  # This should trigger when tapping the Action in check-run.yml, search for "my-check-action".
  # But it doesn't, see https://github:com/github-community/community/discussions/19069
  check_run:
#    types:
#      - requested_action

  # To work around not getting the event, allow manual click.
  workflow_dispatch:
jobs:
  custom-check-run-action:
    name: Reaction to Check Run Action click
#    if: github.event.requested_action.identifier == 'my-check-action'
    runs-on: ubuntu-latest
    steps:
      - name: "Update a check run"
        uses: actions/github-script@v6
        env:
          # Workaround for https://github:com/github-community/community/discussions/19069.
          ref: ${{github.ref}}
        with:
          debug: ${{ secrets.ACTIONS_STEP_DEBUG || false }}
          script: |
            const checks = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: process.env.ref,
              check_name: "my-check-name",
            });
            if (checks.total_count !== 1) {
              console.log(checks);
              core.setFailed(`There were ${checks.total_count} checks found, see logs.`);
              return;
            }
            const check = checks[0];
            if (check.conclusion !== "action_required") {
              console.log(checks);
              core.setFailed(`Status was already resolved as ${check.conclusion}, can't proceed.`);
              return;
            }
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: check.id,
              conclusion: "success",
            });
