# Docs: https://docs.github.com/en/rest/checks/runs#create-a-check-run
# Rest: https://octokit.github.io/rest.js/v18#checks-create

name: Custom Check Run
on:
  workflow_dispatch:
  push:
jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Generate content"
        run: echo -e 'my\nstuff\nwith some `code`' > output.txt

      - name: "Create a check run"
        uses: actions/github-script@v6
        with:
          debug: ${{ secrets.ACTIONS_STEP_DEBUG || false }}
          script: |
            var fs = require('fs');
            var path = require('path');
            var contents = fs.readFileSync("output.txt", { encoding: "utf8" });
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "my-check-name",
              status: "completed",
              conclusion: "success",
              output: {
                title: "my *check* title",
                summary: "my *check* summary",
                text: contents,
              }
            });
