# Docs: https://docs.github.com/en/rest/commits/statuses#create-a-commit-status
# Rest: https://octokit.github.io/rest.js/v18#repos-create-commit-status

name: Custom Commit Status
on:
  push:
jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout ${{ github.ref }} branch in ${{ github.repository }} repository.
        uses: actions/checkout@v3

      - name: "Start a status 1"
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: "pending",
              description: "Custom status in container ${{ job.container.id }}!",
              context: 'custom-status1'
            });

      - name: "Start a status 2"
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: "pending",
              description: "Custom status running in path ${{ github.workspace }}!",
              context: 'Custom Status2'
            });

      - name: "Wait a bit"
        run: sleep 5

      - name: "Complete a status 2 - override description"
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: "failure",
              description: "Custom status completed in path ${{ github.workspace }}!",
              context: 'Custom Status2'
            });


      - name: "Wait a bit"
        run: sleep 5

      - name: "Complete a status 1 - just finish"
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              // Note: not providing a description will clear it.
              state: "error",
              context: 'custom-status1'
            });
