name: If Conditional Expressions
on:
  workflow_dispatch:
  push:
jobs:
  ifs:
    name: Ifs
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Generate content"
        id: step1
        run: |
          echo 'out-value=something' >> $GITHUB_OUTPUT

      - name: "Outputs"
        env:
          STEP1_OUTPUTS: ${{ toJSON(steps.step1.outputs) }}
        run: echo $STEP1_OUTPUTS

      - name: "Expecting execution"
        if: '"something" == "something"'
        run: echo Executed

      - name: "Expecting skip"
        if: '"something" == "something-else"'
        run: echo Executed

      - name: "Expecting execution"
        if: "\"something\" == \"something\""
        run: echo Executed

      - name: "Expecting skip"
        if: "\"something\" == \"something-else\""
        run: echo Executed

      - name: "Expecting execution"
        if: ${{ steps.step1.outputs.out-value }} == "something"
        run: echo Executed

      - name: "Expecting execution (bug)"
        # Equivalent to if: 'something == "something-else"'
        if: ${{ steps.step1.outputs.out-value }} == "something-else"
        run: echo Executed

      - name: "Expecting execution"
        if: ${{ steps.step1.outputs.out-value }} == 'something'
        run: echo Executed

      - name: "Expecting skip"
        if: ${{ steps.step1.outputs.out-value }} == 'something-else'
        run: echo Executed

      - name: "Expecting skip"
        if: ${{ steps.step1.outputs.out-value == 'something-else' }}
        run: echo Executed

      - name: "Expecting execution"
        if: ${{ steps.step1.outputs.out-value == 'something' }}
        run: echo Executed

      #- name: "Expecting compile fail"
      #  if: ${{ steps.step1.outputs.out-value == "something" }}
      #  run: echo Executed

      - name: "Expecting skip"
        if: steps.step1.outputs.out-value == 'something-else'
        run: echo Executed

      - name: "Expecting execution"
        if: steps.step1.outputs.out-value == 'something'
        run: echo Executed
