name: "Local actions"

on:
  workflow_dispatch:

jobs:
  local:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Local action from repo root."
        uses: ./actions/composite-echo

  subfolder:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4
        with:
          path: subfolder
          sparse-checkout: |
            actions/composite-echo

      - name: "Local action in subfolder."
        uses: ./subfolder/actions/composite-echo

  sibling:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4
        with:
          path: sibling
          sparse-checkout: |
            actions/composite-echo

      - name: "Move clone outside working dir"
        run: mv sibling ..

      - name: "Local action outside repo root."
        uses: ./../sibling/actions/composite-echo
