name: Mixed attempts
on:
  workflow_dispatch:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: "Do something 1"
        run: sleep 10
      - name: "Do something 2"
        run: sleep 10
      - name: "Do something 3"
        run: sleep 10
      - name: "Do something 4"
        run: sleep 10
      - name: "Do something 5"
        run: sleep 10
      - name: "Do something 6"
        run: sleep 10
      - name: "Do something 7 (should time out around here)"
        run: sleep 10
      - name: "Do something 8"
        run: sleep 10
