on:
  push:

jobs:
  job1:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: 'false'

  job2:
    if: failure()
    needs:
      - job1
    runs-on: ubuntu-latest
    steps:
      - env:
          NEEDS: ${{ toJSON(needs) }}
        run: |
          echo "${NEEDS}"
