name: Outputs
on:
  workflow_dispatch:
  push:
jobs:
  outputs:
    name: 🔨 Outputs
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Generate content"
        id: step1
        run: |
          echo $GITHUB_OUTPUT
          echo 'out-value=value' >> $GITHUB_OUTPUT
          echo 'out-value-string="value"' >> $GITHUB_OUTPUT
          echo 'out-empty=' >> $GITHUB_OUTPUT
          echo 'out-empty-string=""' >> $GITHUB_OUTPUT
          echo 'out-null=null' >> $GITHUB_OUTPUT
          #echo 'out-missing=' >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: "Outputs"
        env:
          STEP1_OUTPUTS: ${{ toJSON(steps.step1.outputs) }}
        run: echo $STEP1_OUTPUTS

      - name: "Read content"
        run: |
          echo 'out-value=${{ steps.step1.outputs.out-value }}'
          echo 'out-value-string=${{ steps.step1.outputs.out-value-string }}'
          echo 'out-empty=${{ steps.step1.outputs.out-empty }}'
          echo 'out-empty-string=${{ steps.step1.outputs.out-empty-string }}'
          echo 'out-null=${{ steps.step1.outputs.out-null }}'
          echo 'out-missing=${{ steps.step1.outputs.out-missing }}'

      - name: "Read as json"
        # The template is not valid. .github/workflows/outputs.yml (Line: 38, Col: 14): Unexpected character encountered while parsing value: v. Path '', line 0, position 0.
        #echo 'out-value: >>${{ fromJSON(steps.step1.outputs.out-value) }}<<'
        # The template is not valid. .github/workflows/outputs.yml (Line: 40, Col: 14): Error reading JToken from JsonReader. Path '', line 0, position 0.
        #echo 'out-empty: >>${{ fromJSON(steps.step1.outputs.out-empty) }}<<'
        run: |
          echo 'out-value-string: >>${{ fromJSON(steps.step1.outputs.out-value-string) }}<<'
          echo 'out-empty-string: >>${{ fromJSON(steps.step1.outputs.out-empty-string) }}<<'
          echo 'out-null: >>${{ fromJSON(steps.step1.outputs.out-null) }}<<'
          echo 'out-missing: >>${{ fromJSON(steps.step1.outputs.out-missing) }}<<'
