name: "Reusable actions"

on:
  push

env:
  CVERSION: v4
jobs:
  test:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@${{ env.CVERSION }}
