name: "Scripting"

on:
  push:

jobs:

  kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: "Kotlin"
        shell: kotlin -howtorun .main.kts {0}
        run: |
          @file:DependsOn("com.google.code.gson:gson:2.11.0")
          import com.google.gson.Gson
          import java.io.File

          class Event(
            val ref: String,
          )

          val event = Gson().fromJson(File(System.getenv("GITHUB_EVENT_PATH")).readText(), Event::class.java)
          println(event.ref)

  swift:
    runs-on: ubuntu-latest
    steps:
      - name: "Swift"
        shell: swift {0}
        run: |
          print("Hello")

  perligata:
    runs-on: ubuntu-latest
    steps:
      - name: "Perligata"
        shell: sh -c "cpan -qTi Lingua::Romana::Perligata; perl -MLingua::Romana::Perligata {0}"
        run: |
          adnota Illud Cribrum Eratosthenis

          da meo maximo C.
          meis listis conscribementa II tum maximum da.
          dum damentum nexto listis decapitamentum fac
              sic
                  lista sic hoc tum nextum recidementum cis vannementa listis da.
                  dictum tum cum nextum comementum tum novumversum scribe egresso.
              cis
