name: "Scripting"

on:
  push:

jobs:

  kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: "Kotlin"
        shell: kotlin -howtorun .main.kts {0}
        run: |
          @file:DependsOn("com.google.code.gson:gson:2.11.0")
          import com.google.gson.Gson
          import java.io.File

          class Event(
            val ref: String,
          )

          val event = Gson().fromJson(File(System.getenv("GITHUB_EVENT_PATH")).readText(), Event::class.java)
          println(event.ref)

  swift:
    runs-on: ubuntu-latest
    steps:
      - name: "Swift"
        shell: swift {0}
        run: |
          print("Hello")

  perligata:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Lingua::Romana::Perligata"
        run: cpanm --notest Lingua::Romana::Perligata

      - name: "Perligata"
        shell: perl -MLingua::Romana::Perligata -e "{0}"
        run: |
          maximum tum C.
          dixit tum "Primi usque ad C:\n".

          numerus tum II.
          dum numerus minor maximum fac sic
            primus tum I.
            divisor tum II.
            dum divisor minor numerus fac sic
              si numerus modulus divisor aequalis nihil fac sic
                primus tum nihil.
                divisor tum numerus.
              cis
              divisor tum divisor plus I.
            cis
            si primus fac sic
              dixit tum numerus. dixit tum "\n".
            cis
            numerus tum numerus plus I.
          cis
