name: "Scripting"

on:
  push:

jobs:

  kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: "Kotlin"
        shell: kotlin -howtorun .main.kts {0}
        run: |
          @file:DependsOn("com.google.code.gson:gson:2.11.0")
          import com.google.gson.Gson
          import java.io.File

          class Event(
            val ref: String,
          )

          val event = Gson().fromJson(File(System.getenv("GITHUB_EVENT_PATH")).readText(), Event::class.java)
          println(event.ref)

  swift:
    runs-on: ubuntu-latest
    steps:
      - name: "Swift"
        shell: swift {0}
        run: |
          println("Hello")


  debug:
    runs-on: ubuntu-latest
    steps:
      - name: "contents"
        if: always()
        shell: cat {0}
        run: .
      - name: "apos"
        if: always()
        shell: echo '{0}'
        run: .
      - name: "quotes"
        if: always()
        shell: echo "{0}"
        run: .
      - name: "multiple apos"
        if: always()
        shell: echo '{0} {0} {0}'
        run: .
      - name: "multiple quotes"
        if: always()
        shell: echo "{0} {0} {0}"
        run: .

  shebang:
    runs-on: ubuntu-latest
    steps:
      - name: "just"
        if: always()
        shell: '{0}'
        run: |
          #!/usr/bin/swift
          print("Hello")

      - name: "chmod"
        if: always()
        shell: chmod +x {0} && {0}
        run: |
          #!/usr/bin/swift
          print("Hello")

      - name: "bash"
        if: always()
        shell: bash -c 'chmod +x {0} && {0}'
        run: |
          #!/usr/bin/swift
          print("Hello")
