name: "Secret Passing Inner"

on:
  workflow_call:
    secrets:
      TEST_SECRET:
        required: false

jobs:
  without-environment:
    name: "Without Environment"
    runs-on: ubuntu-latest
    steps:
      - name: "Identify secret source."
        env:
          VALUE: ${{ secrets.TEST_SECRET }}
        shell: bash
        # language=bash
        run: |
          case "${VALUE}" in
            "") echo "Secret source: absent." ;;
            "repository-value") echo "Secret source: repository." ;;
            "environment-value") echo "Secret source: environment." ;;
            *) echo "::error::Unexpected secret value."; exit 1 ;;
          esac

  with-environment:
    name: "With Environment"
    environment: "Reusable workflow secret test"
    runs-on: ubuntu-latest
    steps:
      - name: "Identify secret source."
        env:
          VALUE: ${{ secrets.TEST_SECRET }}
        shell: bash
        # language=bash
        run: |
          case "${VALUE}" in
            "") echo "Secret source: absent." ;;
            "repository-value") echo "Secret source: repository." ;;
            "environment-value") echo "Secret source: environment." ;;
            *) echo "::error::Unexpected secret value."; exit 1 ;;
          esac
