on:
  workflow_call:
    inputs:
      input-json:
        required: true
        type: string
    secrets:
      secret-json:
        required: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:

      - name: "Print input"
        env:
          VALUE: ${{ inputs.input-json }}
        shell: bash
        run: echo "${VALUE}"

      - name: "Print secret"
        env:
          VALUE: ${{ secrets.secret-json }}
        shell: bash
        run: echo "${VALUE}"
