# Dependencies and set-output is awesome, but it's easy to make a mistake when substituting text into text and then executing it as code.
# To get structure and somewhat typed, it's better to use fromJSON to gain strictness.

# Note: always() is not relevant here, just there to continue even when erroring.

name: Step Dependencies
on:
  workflow_dispatch:
  push:
jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Do something (success)"
        id: my-passed-step
        run: |
          echo "result-success=true" >> $GITHUB_OUTPUT
          echo "result-text=Some message" >> $GITHUB_OUTPUT

      - name: "Do something (skipped)"
        if: ${{ false }}
        id: my-skipped-step
        run: |
          echo "result-success=false" >> $GITHUB_OUTPUT
          echo "result-text=Some message" >> $GITHUB_OUTPUT

      - name: "Print everything"
        run: |
          echo "steps.my-passed-step: raw=${{ steps.my-passed-step.outputs.result-success }}, toJSON=${{ toJSON(steps.my-passed-step.outputs.result-success) }} -> toJSON(fromJSON)=${{ toJSON(fromJSON(steps.my-passed-step.outputs.result-success)) }}"
          echo "steps.my-failed-step: raw=${{ steps.my-skipped-step.outputs.result-success }}, toJSON=${{ toJSON(steps.my-skipped-step.outputs.result-success) }} -> toJSON(fromJSON)=Error reading JToken from JsonReader."
          echo "steps.my-missing-step: raw=${{ steps.my-missing-step.outputs.result-success }}, toJSON=${{ toJSON(steps.my-missing-step.outputs.result-success) }} -> toJSON(fromJSON)=Error reading JToken from JsonReader."

      - name: "Print success output"
        env:
          XXDIRECT: ${{ steps.my-skipped-step.outputs.result-text }}
          XXFALLBACK: ${{ steps.my-skipped-step.outputs.result-text || '[]' }}
          XXEXPLICIT: ${{ steps.my-skipped-step.outputs.result-text != '' && steps.my-skipped-step.outputs.result-text || '[]' }}
        run: >
          env | grep XX
