name: Step Dependencies
on:
  push:
jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Do something (success)"
        id: my-passed-step
        run: |
          echo ::set-output name=result-success::true
          echo ::set-output name=result-text::Some message

      - name: "Do something (failure)"
        id: my-failed-step
        run: |
          echo ::set-output name=result-success::false
          echo ::set-output name=result-text::Some message

      - name: "Print success output"
        if: ${{ steps.my-passed-step.outputs.result-success }}
        run: echo Success:  with ${{ steps.my-passed-step.outputs.result-text }}

      - name: "Print failed output (negated to make it execute)"
        if: ${{ !steps.my-failed-step.outputs.result-success }}
        run: echo Success: ${{ steps.my-failed-step.outputs.result-success }} with ${{ steps.my-failed-step.outputs.result-text }}

      - name: "Print missing output"
        if: ${{ steps.my-missing-step.outputs.result-success }}
        run: echo Success: ${{ steps.my-missing-step.outputs.result-success }} with ${{ steps.my-missing-step.outputs.result-text }}

      - name: "Print missing output (negated to see how 'nothing translates to boolean')"
        if: ${{ !steps.my-missing-step.outputs.result-success }}
        run: echo Success: ${{ !steps.my-missing-step.outputs.result-success }} with ${{ steps.my-missing-step.outputs.result-text }}
