name: "Stress Test: Multiplier Workflow"

on:
  workflow_dispatch:
  #push:

jobs:
  multiplier:
    uses: ./.github/workflows/stress-multiplied.yml
    strategy:
      matrix:
        counter: [1,2,3,4]
