on: push
jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      content: read
    steps:
      - uses: actions/checkout@v4
      - run: gh pr view
        env:
          GH_TOKEN: ${'$'}{{ github.token }}
